name: Python application

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 14 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi


    - name: environment
      env:
        TI_CLIENT_ID: ${{ secrets.TI_CLIENT_ID }}
        TI_SECRET: ${{ secrets.TI_SECRET }}
        TI_CODE: ${{ secrets.TI_CODE }}
        TI_ACCESS_TOKEN: ${{ secrets.TI_ACCESS_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        bash setup_env.sh
    - name: hero_writer
      run: |
        python hero_writer.py


    - name: environment
      env:
        TI_CLIENT_ID: ${{ secrets.TI_CLIENT_ID }}
        TI_SECRET: ${{ secrets.TI_SECRET }}
        TI_CODE: ${{ secrets.TI_CODE }}
        TI_ACCESS_TOKEN: ${{ secrets.TI_ACCESS_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        bash setup_env.sh
    - name: trend_writer
      run: |
        python trend_writer.py
    - name: cafe_writer
      run: |
        python cafe_writer.py
    

    - name: environment
      env:
        TI_CLIENT_ID: ${{ secrets.TI_CLIENT_ID }}
        TI_SECRET: ${{ secrets.TI_SECRET }}
        TI_CODE: ${{ secrets.TI_CODE }}
        TI_ACCESS_TOKEN: ${{ secrets.TI_ACCESS_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        bash setup_env.sh

    - name: environment
      env:
        TI_CLIENT_ID: ${{ secrets.TI_CLIENT_ID }}
        TI_SECRET: ${{ secrets.TI_SECRET }}
        TI_CODE: ${{ secrets.TI_CODE }}
        TI_ACCESS_TOKEN: ${{ secrets.TI_ACCESS_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        bash setup_env.sh

    
    - name: stock_writer
      run: |
        python stock_writer.py
        

